### ISSUE TITLE
autoIndex true에 관한 d.ts의 설명

### ISSUE THREAD

**Issue by ferrariRoma** [extreme-todo/backend#1]
별 거 아닙니다. 그냥 Issues 너무 안써서 한 번 써보고자 이렇게 정리해 봅니다. 제 작업이 많이 더딤에도 불구하고 이런 짓을 하고 있는 모습을 보시면 혀를 차 실 거 잘 알지만, 죄송합니다 ㅜㅜ Decorator도 그렇고 너무 궁금한 게 많네요 ㅠ 그래도 반성을 하고 좀 더 속도를 내려고 하고 있으니 너그러운 용서 부탁드리겠습니다.

사안은 다음과 같습니다.
`@Schema({ timestamps: { createdAt: 'createdAt' }, autoIndex: true })`

여기서 autoIndex가 무엇인지에 대해서 희정님이 설명을 해주셨는데 '스키마의 설정에 이것 밖에 없나?'하는 생각이 들어서 그냥 d.ts에 들어가서 찾아보게 되었습니다. nestJS나 이런 곳에서는 자세한 설명을 찾을 수 없어서 어디서 찾을까 하다가 그냥 d.ts를 들어갔는데 설명이 굉장히 잘 적혀 있더라고요.

설명은 다음과 같습니다.
By default, Mongoose's "init() function" creates all the indexes defined in your model's schema by calling "Model.createIndexes()" after you successfully connect to MongoDB. If you want to disable automatic index builds, you can set autoIndex to false.

즉 기본적으로 몽구스는 init 함수를 통해서 인덱스를 생성한다고 합니다. 하지만 우리가 이 자동적인 인덱스 생성을 원하지 않는다면 false로 해두면 된다고 하더라고요. 그래서 이걸 true로 안해둬도 되겠다는 판단이 들었습니다.
혹여나 작업 중에 _id가 자동적으로 생기지 않는다면 제가 책임지고 추가하도록 하겠습니다!ㅋㅋ

이상입니다~

**Comment by imhjnoh** [comment]
저는 이 때 index 필드용으로 해뒀던 거였는데, 저희 스키마에서 index가 사라졌으니 필요없을 것 같습니다!
다만 create 외의 작업에서는 _id 를 사용할 일이 있을 수 있으니, 
오브젝트ID 부분은 @Props 데코레이터를 사용하지 않고 타입만 정의해주었습니다. 
feature/todo 확인해주시면 될 것 같습니다!

https://github.com/extreme-todo/backend/blob/d84c9a054b2c912ced2e7debf998238eea6e2a6d/src/todo/schemas/todo.schema.ts#L6-L8
